import random

motivational_phrases = [
    "You are stronger than you think, braver than you feel, and smarter than you know.",
    "Every accomplishment starts with a single step.",
    "You can't turn back the clock. But you can wind it up again.",
    "Great work happens by focusing consistently on something you're genuinely interested on",
    "Don't compare yourself to others; compare yourself to who you were yesterday.",
    "The only thing holding you back is your own self-doubt.",
    "Your only limit is your own mind.",
    "Don't let fear hold you back - face it head-on.",
    "Keep going, even when you don't feel like it.",
    "You are stronger than your excuses.",
    "Don't be afraid to ask for help - that's what friends are for.",
    "The best way to get started is to quit talking and begin doing.",
    "The biggest mistake is giving up on your dreams.",
    "Do something today your tomorrow self will thank you for.",
    "Don't give up - you never know what tomorrow will bring.",
    "Success is not about being perfect; it's about being persistent.",
    "Keep pushing forward, even when the road gets rough.",
    "You are capable of achieving anything you set your mind to.",
    "There is always hope.",
    "Push through the hard times; they're preparing you for better days.",
    "Even the smallest person can change the course of the future.",
    "Procrastinating puts you back in a place of comfort.",
    "The world is not in your books and maps, it's out there.",
    "Success is a journey, not a destination.",
    "The biggest risk is not taking any risk at all.",
    "Your mindset determines your outcome.",
    "Your thoughts have the power to shape your reality.",
    "A wizard is never late, nor is he early, he arrives precisely when he means to.",
    "Don't be afraid to take risks - that's where the magic happens.",
    "Believe in yourself, anything is possible.",
    "Take action today; don't put it off until tomorrow.",
    "Every step forward is a step closer to your dream.",
    "Take control of your life and make today count.",
    "Don't watch the clock; do what it does - keep going.",
    "You are capable of amazing things, just trust yourself.",
    "Success is not final, failure is not fatal: it's the courage to continue that counts.",
    "Keep going, even when it feels like giving up is the easy way out.",
    "You are one decision away from a totally different life.",
    "Keep pushing forward, even when it feels like nothing is happening.",
    "Courage will now be your best defense against the storm that is at hand.",
    "You are one step away from changing everything.",
    "Keep going, even when it feels like nothing is happening.",
    "Believe in yourself and you'll be unstoppable.",
    "The only way to do great work is to love what you do.",
    "Believe in yourself and your abilities.",
    "All we have to decide is what to do with the time that is given us.",
    "Even one step a day gets you 365 steps farther in a year.",
]


def get_motivational_phrase():
    return random.choice(motivational_phrases)
